upstream backend {
       server 192.168.247.128:8000;
       server 192.168.247.128:8001;
       server 192.168.247.128:8002;
}              

server {
	listen 443 ssl;

	ssl_certificate_key  /etc/ssl/private/nginx-selfsigned.key;
	ssl_certificate      /etc/ssl/certs/nginx-selfsigned.crt;

        location / {
                proxy_pass http://backend;
        }
}

server {
	listen 8080;
	listen 80;
	return 301 https://192.168.247.128;
}
